- name: Mise à jour configuration sshd
  copy:
    src: "{{playbook_dir}}/../files/sshd/sshd_config"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0640
  notify:
    - restart-sshd

- name: Validate sshd Config
  shell:
    cmd: sshd -t

- name: Ensure group "mna" exists
  group:
    name: mna
    state: present

- name: Setup password policy in Ubuntu 22.04
  when: ansible_facts['distribution_major_version'] != '24'
  block:
    - name: Install pam packages
      apt:
        name: [ 'libpam-cracklib' ]

    - name: Set password policy
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: "pam_cracklib.so"
        line: "password   requisite   pam_cracklib.so retry=3 minlen=14 difok=3 dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1"

# cracklib is deprecated and removed in Ubuntu 24.04
- name: Setup password policy in Ubuntu 24.04
  when: ansible_facts['distribution_major_version'] == '24'
  block:
    - name: Install pam packages
      apt:
        name: [ 'libpam-pwquality' ]

    - name: Set password policy
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: "pam_pwquality.so"
        line: "password   requisite   pam_pwquality.so retry=3 minlen=14 difok=3 dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1"

- name: Set umask=077 for root user
  lineinfile:
    path: /root/.bashrc
    regexp: '^umask$'
    line: 'umask 0077'

- name: Enable color in sudo
  shell:
    cmd: sudo sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/' /root/.bashrc

- name: Set default umask
  lineinfile:
    path: /etc/pam.d/common-session
    regexp: '^session optional			pam_umask.so$'
    line: 'session optional pam_umask.so umask=0027'

- name: Set default directory /opt/app
  lineinfile:
    path: /root/.bashrc
    regexp: '^cd /opt/app$'
    line: 'cd /opt/app'
