- name: "Installation du paquet 'ipset'"
  apt:
    name: ["ipset"]

- name: "Ajout d'une tâche récurrente pour bloquer les adresses IPs depuis une liste quotidienne"
  ansible.builtin.cron:
    name: "blacklist_ips"
    minute: "0"
    hour: "4"
    job: "bash /opt/app/tools/jail/blacklist-ips.sh >> /var/log/cron.log 2>&1; /opt/app/tools/monitoring/export-cron-status-prom.sh -c 'Backlist IPs' -v $?"
