- name: Install fail2ban packages
  apt:
    name: ["fail2ban"]
  when: ansible_facts['distribution_major_version'] != '23'

- name: start-fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started

- name: Copy fail2ban actions
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/action.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "{{playbook_dir}}/../files/fail2ban/action.d/*"
  notify: restart-fail2ban

- name: Copy fail2ban filters
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/filter.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "{{playbook_dir}}/../files/fail2ban/filter.d/*"
  notify: restart-fail2ban

- name: Copy fail2ban jails
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/fail2ban/jail.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "{{playbook_dir}}/../files/fail2ban/jail.d/*"
  notify: restart-fail2ban
