- name: Création du fichier /opt/app/system/nginx/error.log # Requis pour la config fail2ban
  file:
    path: /opt/app/system/nginx/error.log
    group: adm
    owner: 101 # 101 is the user id of the nginx user
    state: touch

- name: Mise à jour des permissions /opt/app/system/nginx
  file:
    path: /opt/app/system/nginx
    group: adm
    owner: 101 # 101 is the user id of the nginx user
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes

- name: Mise à jour des permissions /opt/app/system/fluentd
  file:
    path: /opt/app/system/fluentd
    group: adm
    owner: root
    mode: "u=rwX,g=rwX,o=rX"
    recurse: yes

- name: Nettoyage des permissions sudo pour le groupe '{{user_group}}'
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "{{user_group}}"

- name: Copie du fichier docker-compose.system.yml
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/app/docker-compose.system.yml"
  with_fileglob:
    - "{{playbook_dir}}/../files/app/docker-compose.system.yml.jinja2"

- name: Démarrage des services systèmes Docker Swarm
  ansible.builtin.shell:
    chdir: /opt/app
    cmd: docker stack deploy --detach=false -c /opt/app/docker-compose.system.yml {{ product_name }}
  async: 1800
  poll: 10
  when:
    - network.stdout == ""
    - env_type != 'preview' and product_name != 'monitoring' and product_name != 'data'

- name: Démarrage des services systèmes Docker Compose
  ansible.builtin.shell:
    chdir: /opt/app
    cmd: docker compose -f /opt/app/docker-compose.system.yml up -d --wait
  async: 1800
  poll: 10
  when:
    - network.stdout == ""
    - env_type == 'preview' or product_name == 'monitoring' or product_name == 'data'

- name: Root only pour tous les répertoires applicatifs
  file:
    path: "/opt/app"
    state: directory
    owner: root
    group: root
    mode: 770

- name: Install htpasswd
  apt:
    name: [apache2-utils]

- name: Create monitoring access file
  shell: htpasswd -bBc "/opt/app/configs/reverse_proxy/locations/monitoring.htpasswd" monitoring {{ vault.MONITORING_PASSWORD }}
