- name: Création des répertoires app/tools & app/configs -> /opt/app
  file:
    path: "/opt/app/{{ item.path }}/"
    state: directory
  with_filetree: "{{playbook_dir}}/../files/app"
  when: item.state == 'directory'

- name: Copie des fichiers 'app'
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/opt/app/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{playbook_dir}}/../files/app"
  when:
    - item.state == 'file'
    - item.path | regex_search('\.jinja2$') == none
    - item.path | basename != '.gitkeep'
    - item.path | basename != '.DS_Store'

- name: Copie des template de l'arborescence /opt/app
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/app/{{ (item.path | splitext)[0] }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{playbook_dir}}/../files/app"
  when:
    - item.state == 'file'
    - item.path | regex_search('\.jinja2$') != none
    - item.path | basename != '.gitkeep'
    - item.path | basename != '.DS_Store'

- name: Création du fichier /opt/app/system/nginx/error.log # Requis pour la config fail2ban
  file:
    path: /opt/app/system/nginx/error.log
    group: adm
    owner: 101 # 101 is the user id of the nginx user
    state: touch

- name: Mise à jour des permissions /opt/app/system/nginx
  file:
    path: /opt/app/system/nginx
    group: adm
    owner: 101 # 101 is the user id of the nginx user
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes

- name: Mise à jour des permissions /opt/app/system/fluentd
  file:
    path: /opt/app/system/fluentd
    group: adm
    owner: root
    mode: "u=rwX,g=rwX,o=rX"
    recurse: yes

- name: Nettoyage des permissions sudo pour le groupe '{{user_group}}'
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "{{user_group}}"

- name: copy du fichier docker compose
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/app/docker-compose.system.yml"
  with_fileglob:
    - "{{playbook_dir}}/../files/app/docker-compose.system.yml"

- name: récupération du status de docker swarm
  ansible.builtin.shell: docker info --format={% raw %}'{{.Swarm.LocalNodeState}}'{% endraw %}
  register: docker_swarm_status
  when: env_type != 'preview'

- name: initialisation de docker swarm
  ansible.builtin.shell: docker swarm init --advertise-addr "{{ ansible_default_ipv4.address }}"
  when:
    - env_type != 'preview'
    - docker_swarm_status.stdout.find('inactive') != -1

- name: check du docker network
  ansible.builtin.shell:
    chdir: /opt/app
    cmd: docker network ls --filter name={{docker_network}} -q
  register: network

- debug:
    var: network

- name: création du docker network en swarm mode
  ansible.builtin.shell:
    chdir: /opt/app
    cmd: docker network create -d overlay --attachable {{docker_network}}
  when:
    - network.stdout == ""
    - env_type != 'preview'

- name: création du docker network en compose mode
  ansible.builtin.shell:
    chdir: /opt/app
    cmd: docker network create --attachable {{docker_network}}
  when:
    - network.stdout == ""
    - env_type == 'preview'

- name: Root only pour tous les répertoires applicatifs
  file:
    path: "/opt/app"
    state: directory
    owner: root
    group: root
    mode: 770

- name: Install htpasswd
  apt:
    name: [apache2-utils]

- name: Create monitoring access file
  shell: htpasswd -bBc "/opt/app/configs/reverse_proxy/locations/monitoring.htpasswd" monitoring {{ vault.MONITORING_PASSWORD }}
