---
- hosts: all
  become: true
  vars_files:
    - "{{playbook_dir}}/../../products/infra/vault/vault.yml"
  tasks:
    - name: Rotate password for user deploy
      ansible.builtin.shell:
        chdir: "/opt/app"
        cmd: "usermod -p '{{ vault[product_name][env_type].GH_USER_PASS_HASH }}' deploy"
