---
- hosts: all
  become: true
  tasks:
    - name: Rotate password for user deploy
      ansible.builtin.shell:
        chdir: "/opt/app"
        cmd: "usermod -p '{{ vault.MNA_GH_USER_PASS_HASH }}' deploy"
