#!/usr/bin/env bash

set -euo pipefail

export PRODUCT_NAME=infra
export GITHUB_ORGANIZATION=mission-apprentissage
export REPO_INFRA=mission-apprentissage/infra
export OP_VAULT_PASSWORD=mna-vault-passwords-common
export OP_ACCOUNT=mission-apprentissage.1password.com
export USER_GROUP=mna

export BIN_DIR="$(dirname -- "$( readlink -f -- "$0"; )")"
export BIN_SHARED_DIR="$BIN_DIR/shared"
export ROOT_DIR="$(dirname "${BIN_DIR}")"
export SCRIPT_DIR="$BIN_DIR/scripts"
export SCRIPT_SHARED_DIR="$BIN_SHARED_DIR/scripts"

. "${BIN_DIR}/commands.sh"

################################################################################
################################################################################
# Main program                                                                 #
################################################################################
################################################################################

readonly command=${1:-}
if [ -z "$command" ]; then
  _help
fi
shift

if [[ `command -v $command` != $command ]]; then
  echo "Err: Command '$command' not found"
  echo
  _help
fi

if [ -z "${CI:-}" ]; then
  dev:dependencies:check
fi

"${SCRIPT_DIR}/ensure-gh-op-auth.sh"

$command "$@"

