name: Run Setup
on:
  workflow_call:
    inputs:
      product:
        description: The product
        type: string
        required: true
      environment:
        description: The environment to setup
        type: string
        required: true
      SSH_KNOWN_HOSTS:
        description: The product SSH_KNOWN_HOSTS
        type: string
        required: true
    secrets:
      DEPLOY_SSH_PRIVATE_KEY:
        description: SSH private key
        required: true
      DEPLOY_PASS:
        description: SSH PWD TO DEPLOY
        required: true
      SLACK_WEBHOOK_ALERTS:
        description: Slack webhook URL
        required: true
      SLACK_WEBHOOK_NOTIF:
        description: Slack webhook URL
        required: true
      OVH_APP_TOKEN:
        description: OVH Application token
        required: true
      OVH_APP_KEY:
        description: OVH Application key
        required: true
      OVH_APP_SECRET:
        description: OVH Application secret
        required: true
      INFRA_OPENPGP_PRIVATE_SUBKEY:
        description: Github Actions' OpenPGP private subkey
        required: true
      PRODUCT_OPENPGP_PRIVATE_SUBKEY:
        description: Github Actions' OpenPGP private subkey
        required: true
      TOKEN_MNA_SHARED:
        description: Authentication token for accessing private repositories
        required: true

jobs:

  npm-packages-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Clone mna-npm-check repository
        uses: actions/checkout@v6
        with:
          repository: mission-apprentissage/mna-npm-check
          path: mna-npm-check

      - name: Analyze NPM dependancies
        run: mna-npm-check/npm-check.sh -p .bin/scripts/ovh/ovh-nodejs-client

      - name: Notify failure on Slack
        uses: slackapi/slack-github-action@v2
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_ALERTS }}
          webhook-type: incoming-webhook
          payload: |
            attachments:
              - color: "danger"
                fallback: "Setup ${{ inputs.product }}-${{ inputs.environment }} a échoué. Suspected traces of known attacks on the NPM supply chain!"
                title: "Setup ${{ inputs.product }}-${{ inputs.environment }} a échoué"
                title_link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                text: "<!channel> *[${{ inputs.product }}-${{ inputs.environment }}]* *${{ github.workflow }}* failed in <${{ github.server_url }}/${{ github.repository }}|${{ github.ref_name }}> on <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>. Suspected traces of known attacks on the NPM supply chain!"
                fields:
                  - title: "Branch"
                    value: "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    short: true
                  - title: "Commit"
                    value: "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    short: true

  setup:
    if: ${{ success() }}
    needs: ["npm-packages-check"]
    concurrency:
      group: "${{ inputs.product }}-${{ inputs.environment }}-${{ github.workflow }}-${{ github.ref }}"
    name: Setup ${{ inputs.product }}-${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:

      - name: Notify new deployment on Slack
        uses: slackapi/slack-github-action@v2
        if: always()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_NOTIF }}
          webhook-type: incoming-webhook
          payload: |
            attachments:
              - color: "#808080"
                fallback: "Setup ${{ inputs.product }}-${{ inputs.environment }} initié..."
                title: "Setup ${{ inputs.product }}-${{ inputs.environment }} initié..."
                title_link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Checkout project
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.TOKEN_MNA_SHARED }}
          submodules: "true"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd .bin/scripts/ovh/ovh-nodejs-client; npm ci --ignore-scripts

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github_actions
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ inputs.SSH_KNOWN_HOSTS }}
          config: |
            Host *
              IdentityFile ~/.ssh/github_actions

      - name: Initialize the GnuPG keyring
        run: |
          echo -n "$INFRA_OPENPGP_KEY" | gpg --import
          echo -n "$PRODUCT_OPENPGP_KEY" | gpg --import
        env:
          INFRA_OPENPGP_KEY: ${{ secrets.INFRA_OPENPGP_PRIVATE_SUBKEY }}
          PRODUCT_OPENPGP_KEY: ${{ secrets.PRODUCT_OPENPGP_PRIVATE_SUBKEY }}

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2

      - name: Run playbook
        run: ".bin/infra system:setup ${{ inputs.product }} ${{ inputs.environment }}"
        env:
          ANSIBLE_REMOTE_USER: deploy
          ANSIBLE_BECOME_PASS: ${{ secrets.DEPLOY_PASS }}
          APP_TOKEN: ${{ secrets.OVH_APP_TOKEN }}
          APP_KEY: ${{ secrets.OVH_APP_KEY }}
          APP_SECRET: ${{ secrets.OVH_APP_SECRET }}

      - name: Encrypt logs
        run: .bin/infra app:deploy:log:encrypt
        if: always()

      - name: Upload logs artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ inputs.product }}-${{ inputs.environment }}
          path: /tmp/deploy.log.gpg

      - name: Add Job summary
        if: always()
        run: echo 'You can get logs using `.bin/infra app:deploy:log:decrypt ${{ github.run_id }} ${{ inputs.product }}-${{ inputs.environment }}`' >> $GITHUB_STEP_SUMMARY

      - name: Notify failure on Slack
        uses: slackapi/slack-github-action@v2
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_ALERTS }}
          webhook-type: incoming-webhook
          payload: |
            attachments:
              - color: "danger"
                fallback: "Setup ${{ inputs.product }}-${{ inputs.environment }} a échoué"
                title: "Setup ${{ inputs.product }}-${{ inputs.environment }} a échoué"
                title_link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                text: "<!channel> *[${{ inputs.product }}-${{ inputs.environment }}]* *${{ github.workflow }}* failed in <${{ github.server_url }}/${{ github.repository }}|${{ github.ref_name }}> on <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>. You can get error logs using `.bin/infra app:deploy:log:decrypt ${{ github.run_id }} ${{ inputs.product }}-${{ inputs.environment }}`"
                fields:
                  - title: "Branch"
                    value: "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    short: true
                  - title: "Commit"
                    value: "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    short: true

      - name: Notify success on Slack
        uses: slackapi/slack-github-action@v2
        if: success()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_NOTIF }}
          webhook-type: incoming-webhook
          payload: |
            attachments:
              - color: "good"
                fallback: "Setup ${{ inputs.product }}-${{ inputs.environment }} terminé avec succès"
                title: "Setup ${{ inputs.product }}-${{ inputs.environment }} terminé avec succès"
                title_link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                fields:
                  - title: "Branch"
                    value: "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    short: true
                  - title: "Commit"
                    value: "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    short: true
