name: Scheduled Password Rotate
on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  rotate_password:
    strategy:
      fail-fast: false
      matrix:
        product:
          [
            "api",
            "bal",
            "lba",
            "monitoring",
            "tdb",
            "vpn",
            "contrat",
            "data",
            "mongodb",
          ]
        environment:
          [
            "production",
            "recette",
            "preview",
            "pentest",
            "preprod",
            "api",
            "bal_1",
            "bal_2",
            "bal_3",
            "recette_1",
            "api_1",
            "api_2",
            "api_3",
            "lba_1",
            "lba_2",
            "lba_3",
            "tdb_1",
            "tdb_2",
            "tdb_3",
            "contrat",
            "lba",
            "tdb",
          ]
    name: Rotate password ${{ matrix.product }}-${{ matrix.environment }}
    uses: "./.github/workflows/_password-rotate.yml"
    with:
      product: "${{ matrix.product }}"
      environment: "${{ matrix.environment }}"
      SSH_KNOWN_HOSTS: ${{ vars[format('{0}_SSH_KNOWN_HOSTS', matrix.product)] }}
    secrets:
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      VAULT_PWD: ${{ secrets.VAULT_PWD }}
      HABILITATIONS: ${{ secrets[format('{0}_HABILITATIONS', matrix.product)] }}
      OVH_APP_TOKEN: ${{ secrets.OVH_APP_TOKEN }}
      OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
      OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
